
services:
  wwebjs:
    container_name: wwebjs
    image: ghcr.io/axjab/wwebjs
    restart: unless-stopped
    environment:
      REPOSITORY_URL: ${REPOSITORY_URL}
      REPOSITORY_TOKEN: ${REPOSITORY_TOKEN}
      NTFY_URL: ${NTFY_URL}
      NTFY_TOKEN: ${NTFY_TOKEN}
    volumes:
      - /srv/log:/logs
      - /data/wwebjs:/data
      - wwebjs-plugins:/plugins  # pulled from REPOSITORY_URL at deployment
    networks:
      - nats

volumes:
  wwebjs-plugins:

networks:
  nats:
    external: true
